rails-dash-ws2017/config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :orders
    resources :customers
    resources :pumpkins
    root to: 'startpage#welcome'
    # For details on the DSL available
    # within this file,
    # see http://guides.rubyonrails.org/routing.html
  end
end

rails-dash-ws2017/app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  def total
    total=0
     orders.each do |order|
      total+=order.total
    end
    return total
  end
end

rails-dash-ws2017/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :line_items
  has_many :pumpkins, through: :line_items
  # has_many(:pumpkins, {through: :line_items})
  def total
      total=0
       line_items.each do |line_item|
        total+=line_item.price
      end
      return total
  end
end

rails-dash-ws2017/app/models/pumpkin.rb
class Pumpkin < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items


  def self_sort(sort)
    # # if
    # # else
    # #   all
    #
    # end
  end
end

rails-dash-ws2017/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

rails-dash-ws2017/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    line_items = @order.line_items.includes(:pumpkin)
    @li_pumpkin_pairs = line_items.map { |li| [li, li.pumpkin] }
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id)
    end
end

rails-dash-ws2017/app/controllers/pumpkins_controller.rb
class PumpkinsController < ApplicationController
  before_action :set_pumpkin, only: [:show, :edit, :update, :destroy]

  # GET /pumpkins
  # GET /pumpkins.json
  def index
    @pumpkins = Pumpkin.all
  end

  # GET /pumpkins/1
  # GET /pumpkins/1.json
  def show
  end

  # GET /pumpkins/new
  def new
    @pumpkin = Pumpkin.new
  end

  # GET /pumpkins/1/edit
  def edit
  end

  # POST /pumpkins
  # POST /pumpkins.json
  def create
    @pumpkin = Pumpkin.new(pumpkin_params)

    respond_to do |format|
      if @pumpkin.save
        format.html { redirect_to @pumpkin, notice: 'Pumpkin was successfully created.' }
        format.json { render :show, status: :created, location: @pumpkin }
      else
        format.html { render :new }
        format.json { render json: @pumpkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pumpkins/1
  # PATCH/PUT /pumpkins/1.json
  def update
    respond_to do |format|
      if @pumpkin.update(pumpkin_params)
        format.html { redirect_to @pumpkin, notice: 'Pumpkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pumpkin }
      else
        format.html { render :edit }
        format.json { render json: @pumpkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pumpkins/1
  # DELETE /pumpkins/1.json
  def destroy
    @pumpkin.destroy
    respond_to do |format|
      format.html { redirect_to pumpkins_url, notice: 'Pumpkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pumpkin
      @pumpkin = Pumpkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pumpkin_params
      params.require(:pumpkin).permit(:species, :carved, :size, :weight, :price)
    end
end

rails-dash-ws2017/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
  <br>
  <strong>Total: </strong>
  <%= @customer.total%>
</p>
<table>
<tbody>
  <% @customer.orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
        <td><%= order.created_at %></td>
      <td><%= link_to 'Show', order %></td>
  <% end %>
</tbody>
</table>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

rails-dash-ws2017/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HTW</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= t '.app_name' %></h1>
    
    <%= link_to '[EN]', pumpkins_path(locale: 'en') %>
    <%= link_to '[DE]', pumpkins_path(locale: 'de') %>
    <%= yield %>
  </body>
</html>

rails-dash-ws2017/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

This is an order.

<p>
  <strong>Customer:</strong>
  <%= @order.customer.name %>
  <br>
    <strong>Total: </strong>
    <%= @order.total %>
</p>


<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th >Pumpkin</th>
      <th >Price per Pumpkin</th>
      <th >Price</th>
    </tr>
  </thead>

  <tbody>
    <% @li_pumpkin_pairs.each do |line_item,pumpkin| %>
      <tr>
        <td><%= line_item.amount %></td>
        <td><%= pumpkin.species %></td>
        <td><%= pumpkin.price %></td>
        <td><%= line_item.price %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

rails-dash-ws2017/app/views/pumpkins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t '.pumpkins'%></h1>

locale: <%= params[:locale] %>

<%=form_tag pumpkins_path :method => 'get' do %>
 <%=submit_tag "Sort by category"%>
 <%=text_field_tag :sortparam, params[:sortparam] %>
 <%end%>

<table>
  <thead>
    <tr>
      <th>Species</th>
      <th>Carved</th>
      <th>Size</th>
      <th>Weight</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pumpkins.each do |pumpkin| %>
      <tr>
        <td><%= pumpkin.species %></td>
        <td><%= pumpkin.carved %></td>
        <td><%= pumpkin.size %></td>
        <td><%= pumpkin.weight %></td>
        <td><%= pumpkin.price %></td>
        <td><%= link_to 'Show', pumpkin %></td>
        <td><%= link_to 'Edit', edit_pumpkin_path(pumpkin) %></td>
        <td><%= link_to 'Destroy', pumpkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pumpkin', new_pumpkin_path %>

rails-dash-ws2017/app/views/pumpkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Species:</strong>
  <%= @pumpkin.species %>
</p>

<p>
  <% if @pumpkin.carved %>
    I'm already carved!!
  <% else %>
    I will be your next project.
  <% end %> 
</p>

<p>
  <strong>Size:</strong>
  <%= @pumpkin.size %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pumpkin.weight %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pumpkin.price %>
</p>

<%= link_to 'Edit', edit_pumpkin_path(@pumpkin) %> |
<%= link_to 'Back', pumpkins_path %>