config/routes.rb
Rails.application.routes.draw do
  resources :comments
  scope '(:locale)' do
    resources :orders
    resources :customers
    resources :pumpkins
    root to: 'startpage#welcome'
    # For details on the DSL available
    # within this file,
    # see http://guides.rubyonrails.org/routing.html
  end
end

app/models/pumpkin.rb
class Pumpkin < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  def self.search(search)
     if(search)
        find(name: search)
     else
        find(:all)  
end

app/controllers/pumpkins_controller.rb
class PumpkinsController < ApplicationController
  before_action :set_pumpkin, only: [:show, :edit, :update, :destroy]

  # GET /pumpkins
  # GET /pumpkins.json
  def index
    @pumpkins = Pumpkin.all
  end

  # GET /pumpkins/1
  # GET /pumpkins/1.json
  def show
  end

  def search
        @pumpkin = pumpkin.search(params[:search])
  end

  end

  # GET /pumpkins/new
  def new
    @pumpkin = Pumpkin.new
  end

  # GET /pumpkins/1/edit
  def edit
  end

  # POST /pumpkins
  # POST /pumpkins.json
  def create
    @pumpkin = Pumpkin.new(pumpkin_params)

    respond_to do |format|
      if @pumpkin.save
        format.html { redirect_to @pumpkin, notice: 'Pumpkin was successfully created.' }
        format.json { render :show, status: :created, location: @pumpkin }
      else
        format.html { render :new }
        format.json { render json: @pumpkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pumpkins/1
  # PATCH/PUT /pumpkins/1.json
  def update
    respond_to do |format|
      if @pumpkin.update(pumpkin_params)
        format.html { redirect_to @pumpkin, notice: 'Pumpkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pumpkin }
      else
        format.html { render :edit }
        format.json { render json: @pumpkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pumpkins/1
  # DELETE /pumpkins/1.json
  def destroy
    @pumpkin.destroy
    respond_to do |format|
      format.html { redirect_to pumpkins_url, notice: 'Pumpkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pumpkin
      @pumpkin = Pumpkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pumpkin_params
      params.require(:pumpkin).permit(:species, :carved, :size, :weight, :price)
    end
end

app/helpers/pumpkins_helper.rb
module PumpkinsHelper
end

app/views/pumpkins/_form.html.erb
<%= form_with(model: pumpkin, local: true) do |form| %>
  <% if pumpkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pumpkin.errors.count, "error") %> prohibited this pumpkin from being saved:</h2>

      <ul>
      <% pumpkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :species %>
    <%= form.text_field :species, id: :pumpkin_species %>
  </div>

  <div class="field">
    <%= form.label :carved %>
    <%= form.check_box :carved, id: :pumpkin_carved %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :pumpkin_size %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight, id: :pumpkin_weight %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :pumpkin_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pumpkins/edit.html.erb
<h1>Editing Pumpkin</h1>

<%= render 'form', pumpkin: @pumpkin %>

<%= link_to 'Show', @pumpkin %> |
<%= link_to 'Back', pumpkins_path %>

app/views/pumpkins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t '.pumpkins'%></h1>

locale: <%= params[:locale] %>

<% form_tag projects_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag <%=t '.search'%>, :name => nil %>
  </p>
<% end %>

<div>
   <% link_to_unless_current "English", locale:"en" %>
   <% link_to_unless_current "Deutsch", locale: "de" %>
</div>

<table>
  <thead>
    <tr>
      <th><%=t '.species'%></th>
      <th><%=t '.carved'%></th>
      <th><%=t '.size'%></th>
      <th><%=t '.weight'%></th>
      <th><%=t '.price'%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pumpkins.each do |pumpkin| %>
      <tr>
        <td><%= pumpkin.species %></td>
        <td><%= pumpkin.carved %></td>
        <td><%= pumpkin.size %></td>
        <td><%= pumpkin.weight %></td>
        <td><%= pumpkin.price %></td>
        <td><%= link_to <%=t '.show'%>, pumpkin %></td>
        <td><%= link_to <%=t '.edit'%>, edit_pumpkin_path(pumpkin) %></td>
        <td><%= link_to <%=t '.destroy'%>, pumpkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to <%=t '.new_pumpkin'%>, new_pumpkin_path %>

app/views/pumpkins/new.html.erb
<h1>New Pumpkin</h1>

<%= render 'form', pumpkin: @pumpkin %>

<%= link_to 'Back', pumpkins_path %>

app/views/pumpkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t '.species'%></strong>
  <%= @pumpkin.species %>
</p>

<p>
  <% if @pumpkin.carved %>
    I'm already carved!!
  <% else %>
    I will be your next project.
  <% end %>
</p>

<p>
  <strong><%=t '.size'%></strong>
  
  <%= @pumpkin.size %>
</p>

<p>

  <strong><%=t '.weight'%></strong>

  <%= @pumpkin.weight %>
</p>

<p>
  <strong><%=t '.price'%></strong>
  <%= @pumpkin.price %>
</p>

<%= link_to "#{t '.edit'}", edit_pumpkin_path(@pumpkin) %> |
<%= link_to "#{t '.back'}", pumpkins_path %>



<h1><%=t '.comments'%></h1>






<table>
  <thead>
    <tr>

      <th><%=t '.title'%></th>
      <th><%=t '.content'%></th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= link_to"#{t '.show'}", comment %></td>
        <td><%= link_to "#{t '.edit'}", edit_comment_path(comment) %></td>
        <td><%= link_to "#{t '.delete'}", comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>